import { globSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitest/config'
import { defineVitestProject } from '@nuxt/test-utils/config'

const path = (relative: string) => fileURLToPath(new URL(relative, import.meta.url))

const NUXT_TESTS = ['test/nuxt/**/*.test.ts', 'app/features/*/tests/**/*.nuxt.test.ts']

/** Nuxt aliases that plain-Node projects (unit, server) need. */
const alias = {
  '#shared': path('./shared'),
  '#server': path('./server'),
  // The app's own alias, for pure feature code that imports a root util explicitly.
  '~': path('./app'),
  // Generated by `nuxt prepare` (postinstall) from the Better Auth config.
  '#auth/schema': path('./.nuxt/better-auth/schema.sqlite.ts'),
  // Every table NuxtHub knows (ours + Better Auth's with plugins), also generated by 'nuxt prepare'.
  'hub:db:schema': path('./.nuxt/hub/db/schema.mjs'),
}

/** Nitro imports `.md` files as text (the assistant's help guide, D109); the server tests do the same. */
const markdownAsText = {
  name: 'markdown-as-text',
  transform(code: string, id: string) {
    return id.endsWith('.md') ? { code: `export default ${JSON.stringify(code)}`, map: null } : undefined
  },
}

// Tests live next to what they test:
// - feature tests: app/features/<name>/tests/*.test.ts
// - shared code tests: test/unit, test/nuxt, test/e2e
// `*.nuxt.test.ts` runs in the Nuxt environment (auto-imports, components); everything else in plain Node.
export default defineConfig({
  test: {
    projects: [
      {
        resolve: { alias },
        test: {
          name: 'unit',
          include: ['test/unit/**/*.test.ts', 'app/features/*/tests/**/*.test.ts'],
          exclude: ['**/*.nuxt.test.ts'],
          environment: 'node',
        },
      },
      {
        // Server services against an in-memory SQLite database built from the real migrations.
        resolve: { alias },
        plugins: [markdownAsText],
        test: {
          name: 'server',
          // server/tests: shared server utils; server/features/*/tests: features (docs/server/architecture.md → Tests).
          include: ['server/tests/**/*.test.ts', 'server/features/*/tests/**/*.test.ts'],
          environment: 'node',
        },
      },
      {
        // The global setup seeds the e2e server's database through the server's own services (D95).
        resolve: { alias },
        test: {
          name: 'e2e',
          include: ['test/e2e/**/*.test.ts'],
          environment: 'node',
          // Builds and serves the app once for all e2e files.
          globalSetup: ['test/e2e/support/global-setup.ts'],
          testTimeout: 30_000,
          // expect.poll defaults to 1 s: too short for a cold page (session check → refresh → redirect)
          // while the whole suite runs, which made redirect/title assertions flaky.
          expect: { poll: { timeout: 5_000 } },
        },
      },
      // The assistant's quality check calls the real AI provider (spends a little): only on request
      // (`ASSISTANT_EVAL=1 … pnpm vitest run --project eval`), never in CI (D109).
      ...(process.env.ASSISTANT_EVAL
        ? [{
            resolve: { alias },
            plugins: [markdownAsText],
            test: { name: 'eval', include: ['server/features/*/eval/**/*.eval.ts'], environment: 'node', maxConcurrency: 1, fileParallelism: false },
          }]
        : []),
      // Loading Nuxt for this project runs NuxtHub's module setup, which rewrites .data/db/migrations
      // and raced with a running dev server (or another Nuxt process) on Windows, failing the whole
      // run. There are no Nuxt-environment tests yet, so the project exists only once one does.
      ...(globSync(NUXT_TESTS).length
        ? [await defineVitestProject({ test: { name: 'nuxt', include: NUXT_TESTS, environment: 'nuxt' } })]
        : []),
    ],
  },
})
