import { sql } from 'drizzle-orm'
import { integer, text } from 'drizzle-orm/sqlite-core'

/**
 * Column helpers shared by the application tables (docs/plans/fullstack-backend.md → Conventions).
 * Column names are snake_case in SQL: NuxtHub and the test database use drizzle's
 * `casing: 'snake_case'`, so TypeScript keys stay camelCase.
 */

/** Opaque text id (UUID v4), generated by the application (D40). */
export const id = () => text().primaryKey().$defaultFn(() => crypto.randomUUID())

/** UTC instant in milliseconds, the same encoding Better Auth uses. */
export const timestamp = () => integer({ mode: 'timestamp_ms' })

const now = sql`(cast(unixepoch('subsecond') * 1000 as integer))`

export const createdAt = () => timestamp().notNull().default(now)
export const updatedAt = () => timestamp().notNull().default(now).$onUpdate(() => new Date())

/** Optimistic concurrency: a write names the version it read; a stale one changes no row (409). */
export const version = () => integer().notNull().default(1)

export const STATUSES = ['ACTIVE', 'INACTIVE'] as const
export const status = () => text({ enum: STATUSES }).notNull().default('ACTIVE')
